#ifndef ELEMENT_VALUE_TAG_H
#define ELEMENT_VALUE_TAG_H

enum ElementValueTag
{
  ELEMENT_VALUE_BYTE = 'B',
  ELEMENT_VALUE_CHAR = 'C',
  ELEMENT_VALUE_DOUBLE = 'D',
  ELEMENT_VALUE_FLOAT = 'F',
  ELEMENT_VALUE_INT = 'I',
  ELEMENT_VALUE_LONG = 'J',
  ELEMENT_VALUE_SHORT = 'S',
  ELEMENT_VALUE_BOOLEAN = 'Z',
  ELEMENT_VALUE_STRING = 's',
  ELEMENT_VALUE_ENUM = 'e',
  ELEMENT_VALUE_CLASS = 'c',
  ELEMENT_VALUE_ANNOTATION = '@',
  ELEMENT_VALUE_ARRAY = '['
};

#endif
