#ifndef TYPE_ANNOTATION_TARGET_TYPE_LOCATION_H
#define TYPE_ANNOTATION_TARGET_TYPE_LOCATION_H

enum TypeAnnotationTargetTypeLocation
{
  TARGET_TYPE_LOCATION_CLASSFILE,
  TARGET_TYPE_LOCATION_METHOD_INFO,
  TARGET_TYPE_LOCATION_FIELD_INFO,
  TARGET_TYPE_LOCATION_CODE
};

#endif
