#ifndef CONSTANT_POOL_TAG_H
#define CONSTANT_POOL_TAG_H

enum ConstantPoolTag
{
  CONSTANT_POOL_CLASS = 7u,
  CONSTANT_POOL_FIELD_REF = 9u,
  CONSTANT_POOL_METHOD_REF = 10u,
  CONSTANT_POOL_INTERFACE_METHOD_REF = 11u,
  CONSTANT_POOL_STRING = 8u,
  CONSTANT_POOL_INTEGER = 3u,
  CONSTANT_POOL_FLOAT = 4u,
  CONSTANT_POOL_LONG = 5u,
  CONSTANT_POOL_DOUBLE = 6u,
  CONSTANT_POOL_NAME_AND_TYPE = 12u,
  CONSTANT_POOL_UTF8 = 1u,
  CONSTANT_POOL_METHOD_HANDLE = 15u,
  CONSTANT_POOL_METHOD_TYPE = 16u,
  CONSTANT_POOL_INVOKE_DYNAMIC = 18u
};

#endif // CONSTANT_POOL_TAG_H
