#ifndef METHOD_PARAMETERS_ATTRIBUTE_ACCESS_FLAG_H
#define METHOD_PARAMETERS_ATTRIBUTE_ACCESS_FLAG_H

enum MethodParametersAttributeAccessFlag
{
  ACC_FINAL = 0x0010,
  ACC_SYNTHETIC = 0x1000,
  ACC_MANDATED = 0x8000
};

#endif
