#ifndef ATTRIBUTE_TYPE
#define ATTRIBUTE_TYPE

enum AttributeType {
  // non-required generic attribute types, can probably ignore
  ATTRIBUTE_TYPE_UNKNOWN,
  ATTRIBUTE_TYPE_CONSTANT_VALUE,
  ATTRIBUTE_TYPE_CODE,
  ATTRIBUTE_TYPE_STACK_MAP_TABLE,
  ATTRIBUTE_TYPE_EXCEPTIONS,
  ATTRIBUTE_TYPE_INNER_CLASSES,
  ATTRIBUTE_TYPE_ENCLOSING_METHOD,
  ATTRIBUTE_TYPE_SYNTHETIC,
  ATTRIBUTE_TYPE_SIGNATURE,
  ATTRIBUTE_TYPE_SOURCE_FILE,
  ATTRIBUTE_TYPE_SOURCE_DEBUG_EXTENSION,
  ATTRIBUTE_TYPE_LINE_NUMBER_TABLE,
  ATTRIBUTE_TYPE_LOCAL_VARIABLE_TABLE,
  ATTRIBUTE_TYPE_LOCAL_VARIABLE_TYPE_TABLE,
  ATTRIBUTE_TYPE_DEPRECATED,
  ATTRIBUTE_TYPE_RUNTIME_VISIBILE_ANNOTATIONS,
  ATTRIBUTE_TYPE_RUNTIME_INVISIBLE_ANNOTATIONS,
  ATTRIBUTE_TYPE_RUNTIME_VISIBLE_PARAMETER_ANNOTATIONS,
  ATTRIBUTE_TYPE_RUNTIME_INVISIBLE_PARAMETER_ANNOTATIONS,
  ATTRIBUTE_TYPE_RUNTIME_VISIBILE_TYPE_ANNOTATIONS,
  ATTRIBUTE_TYPE_RUNTIME_INVISIBLE_TYPE_ANNOTATIONS,
  ATTRIBUTE_TYPE_ANNOTATION_DEFAULT,
  ATTRIBUTE_TYPE_BOOTSTRAP_METHODS,
  ATTRIBUTE_TYPE_METHOD_PARAMETERS
};
#endif
