#ifndef VARIABLE_INFO_ITEM_TYPE_H
#define VARIABLE_INFO_ITEM_TYPE_H

enum VariableInfoItemType
{
  VAR_INFO_ITEM_TOP = 0,
  VAR_INFO_ITEM_INTEGER = 1,
  VAR_INFO_ITEM_FLOAT = 2,
  VAR_INFO_ITEM_DOUBLE = 3,
  VAR_INFO_ITEM_LONG = 4,
  VAR_INFO_ITEM_NULL = 5,
  VAR_INFO_ITEM_UNINITIALIZED_THIS = 6,
  VAR_INFO_ITEM_OBJECT = 7,
  VAR_INFO_ITEM_UNINITIALIZED = 8
};

#endif
